"""prep_for_pg_production

Revision ID: 558def2398ca
Revises: b2c3d4e5f6a7
Create Date: 2026-05-05 17:04:54.807772
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '558def2398ca'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuation_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_valuation_models_stock'))

    op.drop_table('valuation_models')
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_financial_statements_stock'))

    op.drop_table('financial_statements')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    op.drop_table('_alembic_tmp_audit_log')
    with op.batch_alter_table('stock_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_stock_scores_stock'))

    op.drop_table('stock_scores')
    with op.batch_alter_table('stock_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_stock_metrics_stock'))

    op.drop_table('stock_metrics')
    with op.batch_alter_table('cashflow_extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cf_runs_stock'))

    op.drop_table('cashflow_extraction_runs')
    with op.batch_alter_table('financial_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_line_items_statement'))

    op.drop_table('financial_line_items')
    op.drop_table('analysis_audit_log')
    with op.batch_alter_table('pdf_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pdf_uploads_stock'))

    op.drop_table('pdf_uploads')
    with op.batch_alter_table('cashflow_staged_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cf_rows_run'))

    op.drop_table('cashflow_staged_rows')
    with op.batch_alter_table('portfolio_news_dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_portfolio_news_dispatches_dispatched_at'))

    op.drop_table('portfolio_news_dispatches')
    with op.batch_alter_table('analysis_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_analysis_stocks_symbol'))
        batch_op.drop_index(batch_op.f('idx_analysis_stocks_user'))

    op.drop_table('analysis_stocks')
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_extraction_jobs_hash'))
        batch_op.drop_index(batch_op.f('idx_extraction_jobs_stock'))

    op.drop_table('extraction_jobs')
    with op.batch_alter_table('peer_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_peer_companies_stock'))

    op.drop_table('peer_companies')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('resource_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('cash_deposits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('portfolio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'KFH'"))
        batch_op.alter_column('deposit_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('bank_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('deposit_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'deposit'"))
        batch_op.alter_column('fx_rate_at_deposit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("(strftime('%s','now'))"))
        batch_op.drop_index(batch_op.f('idx_cash_deposits_user'))
        batch_op.drop_index(batch_op.f('idx_cash_deposits_user_date'))
        batch_op.drop_index(batch_op.f('idx_cashdep_user'))
        batch_op.drop_index(batch_op.f('idx_cashdep_user_ptf'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('source_reference')

    with op.batch_alter_table('external_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('account_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'BROKERAGE'"))
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('current_balance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('last_reconciled_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_ext_accounts_user'))
        batch_op.drop_index(batch_op.f('idx_extacc_user'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('account_number')

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('entry_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('price_per_unit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=True))
        batch_op.alter_column('entry_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('entry_datetime')
        batch_op.drop_column('price')
        batch_op.drop_column('cash_amount')
        batch_op.drop_column('currency')
        batch_op.drop_column('entry_id')

    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('news_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'boursa_kuwait'"))
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'company_announcement'"))
        batch_op.alter_column('published_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('sentiment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'neutral'"))
        batch_op.alter_column('impact',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'informational'"))
        batch_op.alter_column('language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'en'"))
        batch_op.alter_column('fetched_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('content_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_news_category'))
        batch_op.drop_index(batch_op.f('idx_news_published'))
        batch_op.drop_index(batch_op.f('ix_news_category_date'))
        batch_op.drop_index(batch_op.f('ix_news_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_symbols'))
        batch_op.create_index(batch_op.f('ix_news_articles_news_id'), ['news_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)

    with op.batch_alter_table('pfm_assets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('asset_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('value_kwd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_pfmasset_snap'))
        batch_op.create_foreign_key(None, 'pfm_snapshots', ['snapshot_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('pfm_income_expenses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('kind',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('monthly_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_finance_cost',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_gna',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_pfminc_snap'))
        batch_op.create_foreign_key(None, 'pfm_snapshots', ['snapshot_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('pfm_liabilities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('amount_kwd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_current',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_long_term',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_pfmliab_snap'))
        batch_op.create_foreign_key(None, 'pfm_snapshots', ['snapshot_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('pfm_snapshots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('snapshot_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('total_assets',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_liabilities',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('net_worth',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_pfmsnap_user'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('portfolio_cash', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('portfolio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('manual_override',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_ptfcash_user'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('snapshot_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('portfolio_value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('daily_movement',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('beginning_difference',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('deposit_cash',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('accumulated_cash',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('net_gain',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('change_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('roi_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('twr_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('mwrr_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_snap_date'))
        batch_op.drop_index(batch_op.f('idx_snap_user'))
        batch_op.drop_index(batch_op.f('idx_snap_user_date'))
        batch_op.drop_index(batch_op.f('idx_snapshots_user'))
        batch_op.drop_index(batch_op.f('idx_snapshots_user_date'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('deposit_adjustment')

    with op.batch_alter_table('portfolio_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_share', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('symbol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('txn_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('txn_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('shares',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('fees',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_ptxn_date'))
        batch_op.drop_index(batch_op.f('idx_ptxn_portfolio_source'))
        batch_op.drop_index(batch_op.f('idx_ptxn_portfolio_type'))
        batch_op.drop_index(batch_op.f('idx_ptxn_ptf'))
        batch_op.drop_index(batch_op.f('idx_ptxn_stock'))
        batch_op.drop_index(batch_op.f('idx_ptxn_user'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_by')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('price')
        batch_op.drop_column('legacy_txn_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_portfolios_user'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('base_currency')

    with op.batch_alter_table('position_snapshots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('stock_symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('snapshot_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('total_shares',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('avg_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('realized_pnl',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('cash_dividends_received',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'OPEN'"))
        batch_op.drop_index(batch_op.f('idx_pos_snap_status'))
        batch_op.drop_index(batch_op.f('idx_pos_snap_stock'))
        batch_op.drop_index(batch_op.f('idx_pos_snap_user'))
        batch_op.drop_index(batch_op.f('idx_pos_snapshots_date'))
        batch_op.drop_index(batch_op.f('idx_pos_snapshots_stock'))
        batch_op.drop_index(batch_op.f('idx_possn_date'))
        batch_op.drop_index(batch_op.f('idx_possn_symbol'))
        batch_op.drop_index(batch_op.f('idx_possn_user'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('txn_id')

    with op.batch_alter_table('securities_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('symbol', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('asset_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('yahoo_symbol', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('tradingview_symbol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tradingview_exchange', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('market_cap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('outstanding_shares', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=False))
        batch_op.alter_column('exchange',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('sector',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'KW'"))
        batch_op.alter_column('isin',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_secmaster_user'))
        batch_op.drop_index(batch_op.f('idx_securities_country'))
        batch_op.drop_index(batch_op.f('idx_securities_exchange'))
        batch_op.drop_index(batch_op.f('idx_securities_ticker'))
        batch_op.drop_column('canonical_ticker')
        batch_op.drop_column('status')
        batch_op.drop_column('display_name')
        batch_op.drop_column('user_id')
        batch_op.drop_column('security_id')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('portfolio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'KFH'"))
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('current_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('price_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('tradingview_symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tradingview_exchange',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('market_cap',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('sector',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('industry',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('pe_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_stocks_symbol'))
        batch_op.drop_index(batch_op.f('idx_stocks_user'))
        batch_op.drop_index(batch_op.f('idx_stocks_user_portfolio'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('previous_close')
        batch_op.drop_column('created_at')
        batch_op.drop_column('yf_ticker')

    with op.batch_alter_table('stocks_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=50), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('exchange',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'KSE'"))
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text("'KWD'"))
        batch_op.drop_index(batch_op.f('idx_stocks_master_ticker'))
        batch_op.drop_column('sector')
        batch_op.drop_column('isin')
        batch_op.drop_column('status')
        batch_op.drop_column('country')
        batch_op.drop_column('ticker')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('jti',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_token_bl_user'))
        batch_op.create_index(batch_op.f('ix_token_blacklist_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('portfolio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'KFH'"))
        batch_op.alter_column('stock_symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('txn_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('txn_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('shares',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('purchase_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('sell_value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('bonus_shares',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('cash_dividend',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reinvested_dividend',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('fees',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('price_override',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('planned_cum_shares',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('broker',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('reference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_txn_date'))
        batch_op.drop_index(batch_op.f('idx_txn_deleted'))
        batch_op.drop_index(batch_op.f('idx_txn_security_id'))
        batch_op.drop_index(batch_op.f('idx_txn_source'))
        batch_op.drop_index(batch_op.f('idx_txn_source_ref'))
        batch_op.drop_index(batch_op.f('idx_txn_symbol'))
        batch_op.drop_index(batch_op.f('idx_txn_user'))
        batch_op.drop_index(batch_op.f('idx_txn_user_date'))
        batch_op.drop_index(batch_op.f('idx_txn_user_ptf'))
        batch_op.drop_index(batch_op.f('idx_txn_user_symbol'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('portfolio_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('avg_cost_at_txn')
        batch_op.drop_column('stock_master_id')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('source')
        batch_op.drop_column('fx_rate_at_txn')
        batch_op.drop_column('cost_basis_at_txn')
        batch_op.drop_column('realized_pnl_at_txn')
        batch_op.drop_column('shares_held_at_txn')
        batch_op.drop_column('security_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_users_gemini_validated'))
        batch_op.drop_column('email')
        batch_op.drop_column('gemini_api_key_last_validated')
        batch_op.drop_column('gemini_api_key_encrypted')
        batch_op.drop_column('gemini_api_key')
        batch_op.drop_column('google_sub')
        batch_op.drop_column('gemini_quota_reset_at')
        batch_op.drop_column('gemini_requests_today')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_requests_today', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('gemini_quota_reset_at', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('google_sub', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('gemini_api_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('gemini_api_key_encrypted', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('gemini_api_key_last_validated', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('idx_users_gemini_validated'), ['gemini_api_key_last_validated'], unique=False)
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_admin',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('shares_held_at_txn', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('realized_pnl_at_txn', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('cost_basis_at_txn', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_at_txn', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.TEXT(), server_default=sa.text("'MANUAL'"), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('stock_master_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('avg_cost_at_txn', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('source_reference', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_txn_user_symbol'), ['user_id', 'stock_symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_user_ptf'), ['user_id', 'portfolio'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_user_date'), ['user_id', 'txn_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_symbol'), ['stock_symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_source_ref'), ['source_reference'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('idx_txn_date'), ['txn_date'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('reference',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('broker',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('planned_cum_shares',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('price_override',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('fees',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reinvested_dividend',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('cash_dividend',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('bonus_shares',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('sell_value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('purchase_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shares',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('txn_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('txn_date',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('stock_symbol',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('portfolio',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'KFH'"))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_user_id'))
        batch_op.create_index(batch_op.f('idx_token_bl_user'), ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('jti',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('stocks_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ticker', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.TEXT(), server_default=sa.text("'KW'"), nullable=True))
        batch_op.add_column(sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True))
        batch_op.add_column(sa.Column('isin', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('idx_stocks_master_ticker'), ['ticker'], unique=False)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('exchange',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'KSE'"))
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('symbol')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yf_ticker', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('previous_close', sa.REAL(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_stocks_user_portfolio'), ['user_id', 'portfolio'], unique=False)
        batch_op.create_index(batch_op.f('idx_stocks_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_stocks_symbol'), ['symbol'], unique=False)
        batch_op.alter_column('pe_ratio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('industry',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sector',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('market_cap',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('tradingview_exchange',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tradingview_symbol',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('price_source',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('portfolio',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'KFH'"))
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('securities_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('display_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True))
        batch_op.add_column(sa.Column('canonical_ticker', sa.TEXT(), nullable=False))
        batch_op.create_index(batch_op.f('idx_securities_ticker'), ['canonical_ticker'], unique=False)
        batch_op.create_index(batch_op.f('idx_securities_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('idx_securities_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('idx_secmaster_user'), ['user_id'], unique=False)
        batch_op.alter_column('isin',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'KW'"))
        batch_op.alter_column('sector',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('exchange',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('outstanding_shares')
        batch_op.drop_column('market_cap')
        batch_op.drop_column('tradingview_exchange')
        batch_op.drop_column('tradingview_symbol')
        batch_op.drop_column('yahoo_symbol')
        batch_op.drop_column('industry')
        batch_op.drop_column('asset_type')
        batch_op.drop_column('name')
        batch_op.drop_column('symbol')
        batch_op.drop_column('id')

    with op.batch_alter_table('position_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txn_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'portfolios', ['portfolio_id'], ['id'])
        batch_op.create_foreign_key(None, 'stocks_master', ['stock_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_possn_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_possn_symbol'), ['stock_symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_possn_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_pos_snapshots_stock'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pos_snapshots_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_pos_snap_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pos_snap_stock'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pos_snap_status'), ['status'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'OPEN'"))
        batch_op.alter_column('cash_dividends_received',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('realized_pnl',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('avg_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_shares',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('snapshot_date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('stock_symbol',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_currency', sa.TEXT(), server_default=sa.text("'KWD'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_portfolios_user'), ['user_id'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('portfolio_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.TEXT(), server_default=sa.text("'MANUAL'"), nullable=False))
        batch_op.add_column(sa.Column('legacy_txn_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('source_reference', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'external_accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key(None, 'stocks_master', ['stock_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_ptxn_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ptxn_stock'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ptxn_ptf'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ptxn_portfolio_type'), ['portfolio_id', 'txn_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_ptxn_portfolio_source'), ['portfolio_id', 'source'], unique=False)
        batch_op.create_index(batch_op.f('idx_ptxn_date'), ['txn_date'], unique=False)
        batch_op.alter_column('fees',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shares',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
        batch_op.alter_column('txn_date',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('txn_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('reference')
        batch_op.drop_column('description')
        batch_op.drop_column('symbol')
        batch_op.drop_column('fx_rate')
        batch_op.drop_column('currency')
        batch_op.drop_column('price_per_share')

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_adjustment', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_snapshots_user_date'), ['user_id', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_snapshots_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_snap_user_date'), ['user_id', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_snap_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_snap_date'), ['snapshot_date'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mwrr_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('twr_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('roi_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('change_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('net_gain',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('accumulated_cash',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('deposit_cash',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('beginning_difference',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('daily_movement',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('portfolio_value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
        batch_op.alter_column('snapshot_date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('portfolio')

    with op.batch_alter_table('portfolio_cash', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_ptfcash_user'), ['user_id'], unique=False)
        batch_op.alter_column('manual_override',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('portfolio',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('id')

    with op.batch_alter_table('pfm_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_pfmsnap_user'), ['user_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('net_worth',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_liabilities',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_assets',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('snapshot_date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('pfm_liabilities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_pfmliab_snap'), ['snapshot_id'], unique=False)
        batch_op.alter_column('is_long_term',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_current',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('amount_kwd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('pfm_income_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_pfminc_snap'), ['snapshot_id'], unique=False)
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_gna',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_finance_cost',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('monthly_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('kind',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('pfm_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_pfmasset_snap'), ['snapshot_id'], unique=False)
        batch_op.alter_column('value_kwd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('asset_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_news_id'))
        batch_op.create_index(batch_op.f('ix_news_symbols'), ['related_symbols'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_category_date'), ['category', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_news_published'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_news_category'), ['category'], unique=False)
        batch_op.alter_column('content_hash',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fetched_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'en'"))
        batch_op.alter_column('impact',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'informational'"))
        batch_op.alter_column('sentiment',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'neutral'"))
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'company_announcement'"))
        batch_op.alter_column('source',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'boursa_kuwait'"))
        batch_op.alter_column('news_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('cash_amount', sa.REAL(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('entry_datetime', sa.TEXT(), nullable=False))
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['asset_id'])
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('entry_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('fees')
        batch_op.drop_column('total_value')
        batch_op.drop_column('price_per_unit')
        batch_op.drop_column('entry_date')
        batch_op.drop_column('id')

    with op.batch_alter_table('external_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_extacc_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ext_accounts_user'), ['user_id'], unique=False)
        batch_op.alter_column('last_reconciled_date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('current_balance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('account_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'BROKERAGE'"))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('notes')

    with op.batch_alter_table('cash_deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_reference', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_cashdep_user_ptf'), ['user_id', 'portfolio'], unique=False)
        batch_op.create_index(batch_op.f('idx_cashdep_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cash_deposits_user_date'), ['user_id', 'deposit_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_cash_deposits_user'), ['user_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("(strftime('%s','now'))"))
        batch_op.alter_column('fx_rate_at_deposit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('deposit_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'deposit'"))
        batch_op.alter_column('source',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'KWD'"))
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('deposit_date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('portfolio',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'KFH'"))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('peer_companies',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('peer_symbol', sa.TEXT(), nullable=False),
    sa.Column('peer_name', sa.TEXT(), nullable=False),
    sa.Column('sector', sa.TEXT(), nullable=True),
    sa.Column('pe', sa.REAL(), nullable=True),
    sa.Column('pb', sa.REAL(), nullable=True),
    sa.Column('ps', sa.REAL(), nullable=True),
    sa.Column('pcf', sa.REAL(), nullable=True),
    sa.Column('ev_ebitda', sa.REAL(), nullable=True),
    sa.Column('eps', sa.REAL(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('fetched_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'peer_symbol')
    )
    with op.batch_alter_table('peer_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_peer_companies_stock'), ['stock_id'], unique=False)

    op.create_table('extraction_jobs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pdf_upload_id', sa.INTEGER(), nullable=True),
    sa.Column('pdf_hash', sa.TEXT(), nullable=True),
    sa.Column('source_file', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('stage', sa.TEXT(), server_default=sa.text("'uploading'"), nullable=False),
    sa.Column('pages_processed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_pages', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('progress_percent', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('model', sa.TEXT(), server_default=sa.text("'gemini-2.5-flash'"), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('result_payload', sa.TEXT(), nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.INTEGER(), nullable=True),
    sa.Column('last_heartbeat_at', sa.INTEGER(), nullable=True),
    sa.Column('completed_at', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_extraction_jobs_stock'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_extraction_jobs_hash'), ['stock_id', 'pdf_hash'], unique=False)

    op.create_table('analysis_stocks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('company_name', sa.TEXT(), nullable=False),
    sa.Column('exchange', sa.TEXT(), server_default=sa.text("'NYSE'"), nullable=True),
    sa.Column('currency', sa.TEXT(), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('sector', sa.TEXT(), nullable=True),
    sa.Column('industry', sa.TEXT(), nullable=True),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('isin', sa.TEXT(), nullable=True),
    sa.Column('cik', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('outstanding_shares', sa.REAL(), nullable=True),
    sa.Column('summary_margin_of_safety', sa.REAL(), server_default=sa.text('(15.0)'), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol')
    )
    with op.batch_alter_table('analysis_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_analysis_stocks_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_analysis_stocks_symbol'), ['symbol'], unique=False)

    op.create_table('portfolio_news_dispatches',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('news_id', sa.TEXT(), nullable=False),
    sa.Column('dispatched_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    with op.batch_alter_table('portfolio_news_dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_portfolio_news_dispatches_dispatched_at'), ['dispatched_at'], unique=False)

    op.create_table('cashflow_staged_rows',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('row_order', sa.INTEGER(), nullable=False),
    sa.Column('label_raw', sa.TEXT(), nullable=False),
    sa.Column('normalized_code', sa.TEXT(), nullable=True),
    sa.Column('section', sa.TEXT(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('row_kind', sa.TEXT(), server_default=sa.text("'item'"), nullable=False),
    sa.Column('values_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_total', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('is_accepted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['cashflow_extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_staged_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cf_rows_run'), ['run_id'], unique=False)

    op.create_table('pdf_uploads',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.TEXT(), nullable=False),
    sa.Column('original_name', sa.TEXT(), nullable=False),
    sa.Column('pdf_hash', sa.TEXT(), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pdf_uploads_stock'), ['stock_id'], unique=False)

    op.create_table('analysis_audit_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('operation', sa.TEXT(), nullable=False),
    sa.Column('entity_type', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('old_value', sa.TEXT(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_line_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('statement_id', sa.INTEGER(), nullable=False),
    sa.Column('line_item_code', sa.TEXT(), nullable=False),
    sa.Column('line_item_name', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('currency', sa.TEXT(), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.Column('parent_item_id', sa.INTEGER(), nullable=True),
    sa.Column('is_total', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('manually_edited', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('edited_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('edited_at', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['financial_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_line_items_statement'), ['statement_id'], unique=False)

    op.create_table('cashflow_extraction_runs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('pdf_upload_id', sa.INTEGER(), nullable=True),
    sa.Column('source_file', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'extracted'"), nullable=False),
    sa.Column('periods_json', sa.TEXT(), nullable=True),
    sa.Column('raw_model_response', sa.TEXT(), nullable=True),
    sa.Column('reconciliation_summary', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_extraction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cf_runs_stock'), ['stock_id'], unique=False)

    op.create_table('stock_metrics',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('fiscal_year', sa.INTEGER(), nullable=False),
    sa.Column('fiscal_quarter', sa.INTEGER(), nullable=True),
    sa.Column('period_end_date', sa.TEXT(), nullable=False),
    sa.Column('metric_type', sa.TEXT(), nullable=False),
    sa.Column('metric_name', sa.TEXT(), nullable=False),
    sa.Column('metric_value', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'metric_name', 'period_end_date')
    )
    with op.batch_alter_table('stock_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_stock_metrics_stock'), ['stock_id'], unique=False)

    op.create_table('stock_scores',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('scoring_date', sa.TEXT(), nullable=False),
    sa.Column('overall_score', sa.REAL(), nullable=True),
    sa.Column('fundamental_score', sa.REAL(), nullable=True),
    sa.Column('valuation_score', sa.REAL(), nullable=True),
    sa.Column('growth_score', sa.REAL(), nullable=True),
    sa.Column('quality_score', sa.REAL(), nullable=True),
    sa.Column('risk_score', sa.REAL(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('analyst_notes', sa.TEXT(), nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_stock_scores_stock'), ['stock_id'], unique=False)

    op.create_table('_alembic_tmp_audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'general'"), nullable=False),
    sa.Column('action', sa.TEXT(), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('financial_statements',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('statement_type', sa.TEXT(), nullable=False),
    sa.Column('fiscal_year', sa.INTEGER(), nullable=False),
    sa.Column('fiscal_quarter', sa.INTEGER(), nullable=True),
    sa.Column('period_end_date', sa.TEXT(), nullable=False),
    sa.Column('filing_date', sa.TEXT(), nullable=True),
    sa.Column('source_file', sa.TEXT(), nullable=True),
    sa.Column('extracted_by', sa.TEXT(), server_default=sa.text("'manual'"), nullable=True),
    sa.Column('confidence_score', sa.REAL(), nullable=True),
    sa.Column('verified_by_user', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'statement_type', 'period_end_date')
    )
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_financial_statements_stock'), ['stock_id'], unique=False)

    op.create_table('valuation_models',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('model_type', sa.TEXT(), nullable=False),
    sa.Column('valuation_date', sa.TEXT(), nullable=False),
    sa.Column('intrinsic_value', sa.REAL(), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('assumptions', sqlite.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['analysis_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_valuation_models_stock'), ['stock_id'], unique=False)

    # ### end Alembic commands ###
